[2024-07-06T23:29:26.993+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: fetch_from_minio_dag.fetch_minio_data manual__2024-07-06T23:24:06.425133+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
